name: Software Testing 2023 pipeline

on: [push, workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Run tests
        run: mvn verify -Dheadless=true
      - name: Publish html report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: ./target/test-report.html
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save